### ISSUE TITLE
SA, machine learning hk.

### ISSUE THREAD

**Issue by masmm** [idilkubat/MachineLearning#1]
Kullandığınız kaynakları paylaşabilir misiniz? Hep finansa gitmek istemiştim ama başlayacak yer arıyorum.

**Comment by idilkubat** [comment]
Merhaba Mehmet,

Kullandığım kaynaklar şirket özelinde olduğu için paylaşmam imkansız gibi duruyor fakat seninle çalışmalarımı ilerleyen zamanlarda paylaşabilirim. Kendine iyi bak,

İyi çalışmalar dilerim.


masmm <notifications@github.com> şunları yazdı (8 Şub 2021 17:16):

﻿

Kullandığınız kaynakları paylaşabilir misiniz? Hep finansa gitmek istemiştim ama başlayacak yer arıyorum.

**Comment by idilkubat** [comment]
Merhabaaaa 🤸🏻‍♀️

Nasılsın? Neler yapıyorsun? 2 hafta oldu ben gideli hemen bir güncelleme yapalım 😄


masmm <notifications@github.com> şunları yazdı (19 Şub 2021 09:24):

﻿

Closed #1<https://github.com/idilkubat/MachineLearning/issues/1>.

**Comment by masmm** [comment]
bu konuşmayı wapp veya mail üzerinden yapmayı tercih ederim 😄

**Comment by idilkubat** [comment]
Mail üzerinden yapıyoruz 😂


masmm <notifications@github.com> şunları yazdı (19 Şub 2021 12:21):

﻿

bu konuşmayı wapp veya mail üzerinden yapmayı tercih ederim 😄
